# Generated by Django 5.0.1 on 2026-01-30 23:58

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='ელ. ფოსტა')),
                ('role', models.CharField(default='admin', max_length=50, verbose_name='როლი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('is_staff', models.BooleanField(default=True, verbose_name='პერსონალი')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ზედა ადმინი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='ბოლო შესვლა')),
                ('groups', models.ManyToManyField(blank=True, help_text='ამ ადმინისტრატორის ჯგუფები', related_name='admin_users', to='auth.group', verbose_name='ჯგუფები')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='ამ ადმინისტრატორის უფლებები', related_name='admin_users', to='auth.permission', verbose_name='მომხმარებლის უფლებები')),
            ],
            options={
                'verbose_name': 'ადმინისტრატორი',
                'verbose_name_plural': 'ადმინისტრატორები',
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('personal_id', encrypted_model_fields.fields.EncryptedCharField(help_text='11-ციფრიანი პირადი ნომერი', unique=True, verbose_name='პირადი ნომერი')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='ელ. ფოსტა')),
                ('mobile', models.CharField(help_text='+995 XXX XX XX XX ან 5XX XX XX XX', max_length=20, verbose_name='მობილური')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='კომპანიის დასახელება')),
                ('company_id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='საიდენტიფიკაციო კოდი')),
                ('address', models.TextField(blank=True, null=True, verbose_name='მისამართი')),
                ('notes', models.TextField(blank=True, help_text='ადმინისთვის დამატებითი ინფორმაცია', null=True, verbose_name='შენიშვნები')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('must_change_password', models.BooleanField(default=True, help_text='პირველ შესვლაზე უნდა შეიცვალოს პაროლი', verbose_name='პაროლის შეცვლა საჭიროა')),
                ('is_staff', models.BooleanField(default=True, help_text='საჭიროა Django admin-ში შესასვლელად', verbose_name='პერსონალი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='ბოლო შესვლა')),
                ('groups', models.ManyToManyField(blank=True, help_text='ამ მომხმარებლის ჯგუფები', related_name='regular_users', to='auth.group', verbose_name='ჯგუფები')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='ამ მომხმარებლის უფლებები', related_name='regular_users', to='auth.permission', verbose_name='მომხმარებლის უფლებები')),
                ('created_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='accounts.adminuser', verbose_name='შემქმნელი ადმინი')),
            ],
            options={
                'verbose_name': 'მომხმარებელი',
                'verbose_name_plural': 'მომხმარებლები',
                'db_table': 'users',
            },
        ),
    ]
