# Generated by Django 5.0.1 on 2026-02-03 11:15

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_by_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ადმინისტრატორი'), ('client', 'კლიენტი')], default='client', max_length=50, verbose_name='როლი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='ზედა ადმინი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='+995 XXX XX XX XX ან 5XX XX XX XX', max_length=20, null=True, verbose_name='მობილური'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='პირველ შესვლაზე უნდა შეიცვალოს პაროლი', verbose_name='პაროლის შეცვლა საჭიროა'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='11-ციფრიანი პირადი ნომერი', null=True, unique=True, verbose_name='პირადი ნომერი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
