image: docker:stable

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  SERVICE_NAME: 'cargo-menegment-system'
  CI_REGISTRY_IMAGE: 'dockerhub.softgen.ge/babiline/cargo-menegment-system'

stages:
  - build
  - deploy

Build Development:
  stage: build
  cache:
    key: build-cache
    paths:
      - gradle/
  before_script:
    - echo ${DOCKER_REGISTRY_PASSWORD_U} | docker login -u gitlab-runner --password-stdin ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:main ./
    - docker push ${CI_REGISTRY_IMAGE}:main
  only:
    - main

Deploy Development:
  stage: deploy
  before_script:
    - echo ${DOCKER_REGISTRY_PASSWORD_U} | docker -H tcp://192.168.80.230:2375 login -u gitlab-runner --password-stdin ${CI_REGISTRY}
  script:
    - exists=`docker -H tcp://192.168.80.230:2375 service ls -f name=${SERVICE_NAME} -q | wc -l`
    - |
      if [ $exists -eq 0 ]
      then
        docker -H tcp://192.168.80.230:2375 service create  \
          --with-registry-auth                      \
          --restart-delay             10s           \
          --restart-max-attempts      5             \
          --restart-window            20s           \
          --rollback-delay            3s            \
          --rollback-failure-action   pause         \
          --rollback-order            stop-first    \
          --update-delay              1m            \
          --update-failure-action     rollback      \
          --update-order              start-first   \
          --network service_network                 \
          --name ${SERVICE_NAME} \
          nginx
      fi
    - |
      docker -H tcp://192.168.80.230:2375 service update \
        --force \
        --with-registry-auth \
        --env-add DJANGO_DEBUG=true \
        --env-add DB_NAME=${DEV_DB_NAME} \
        --env-add DB_USER=${DEV_DB_USER} \
        --env-add DB_PASSWORD=${DEV_DB_PASSWORD} \
        --env-add DB_HOST=${DEV_DB_HOST} \
        --env-add DB_PORT=${DEV_DB_PORT} \
        --env-add ALLOWED_HOSTS=* \
        --image ${CI_REGISTRY_IMAGE}:main \
        ${SERVICE_NAME}
  only:
    - main
