

services:
  db:
    image: postgres:15
    container_name: cargo-postgres
    environment:
      POSTGRES_DB: cargo_db
      POSTGRES_USER: cargo_user
      POSTGRES_PASSWORD: secret123
    networks:
      - cargo-network
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: cargo-django
    environment:
      DB_HOST: db
      DB_NAME: cargo_db
      DB_USER: cargo_user
      DB_PASSWORD: secret123
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "https://localhost:6048,http://localhost:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cargo-network

  nginx:
    build: ./nginx
    container_name: cargo-nginx
    ports:
      - "6048:443"
    depends_on:
      - web
    networks:
      - cargo-network

networks:
  cargo-network:
    driver: bridge
