# Generated by Django 5.0.1 on 2026-01-30 23:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='დასახელება')),
                ('is_active', models.BooleanField(default=True, help_text='არააქტიური ჩანაწერები არ ჩანს dropdown-ებში', verbose_name='აქტიური')),
                ('sort_order', models.IntegerField(default=0, help_text='ნაკლები რიცხვი = უფრო ადრე გამოჩნდება', verbose_name='დალაგების რიგითობა')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
            ],
            options={
                'verbose_name': 'ტვირთის ტიპი',
                'verbose_name_plural': 'ტვირთის ტიპები',
                'db_table': 'cargo_types',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='დასახელება')),
                ('is_active', models.BooleanField(default=True, help_text='არააქტიური ჩანაწერები არ ჩანს dropdown-ებში', verbose_name='აქტიური')),
                ('sort_order', models.IntegerField(default=0, help_text='ნაკლები რიცხვი = უფრო ადრე გამოჩნდება', verbose_name='დალაგების რიგითობა')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('code', models.CharField(help_text='ISO 4217 კოდი, მაგ: GEL, USD, EUR', max_length=3, unique=True, verbose_name='კოდი')),
                ('symbol', models.CharField(help_text='მაგ: ₾, $, €', max_length=5, verbose_name='სიმბოლო')),
            ],
            options={
                'verbose_name': 'ვალუტა',
                'verbose_name_plural': 'ვალუტები',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='დასახელება')),
                ('is_active', models.BooleanField(default=True, help_text='არააქტიური ჩანაწერები არ ჩანს dropdown-ებში', verbose_name='აქტიური')),
                ('sort_order', models.IntegerField(default=0, help_text='ნაკლები რიცხვი = უფრო ადრე გამოჩნდება', verbose_name='დალაგების რიგითობა')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
            ],
            options={
                'verbose_name': 'ტრანსპორტის ტიპი',
                'verbose_name_plural': 'ტრანსპორტის ტიპები',
                'db_table': 'transport_types',
            },
        ),
        migrations.CreateModel(
            name='VolumeUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='დასახელება')),
                ('is_active', models.BooleanField(default=True, help_text='არააქტიური ჩანაწერები არ ჩანს dropdown-ებში', verbose_name='აქტიური')),
                ('sort_order', models.IntegerField(default=0, help_text='ნაკლები რიცხვი = უფრო ადრე გამოჩნდება', verbose_name='დალაგების რიგითობა')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('abbreviation', models.CharField(help_text='მაგ: კგ, ტ, მ³', max_length=10, verbose_name='შემოკლება')),
            ],
            options={
                'verbose_name': 'მოცულობის ერთეული',
                'verbose_name_plural': 'მოცულობის ერთეულები',
                'db_table': 'volume_units',
            },
        ),
    ]
