# Generated by Django 5.0.1 on 2026-01-30 23:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='კომპანიის დასახელება')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='საკონტაქტო ელ. ფოსტა')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='საკონტაქტო ტელეფონი')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='საკონტაქტო პირი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
            ],
            options={
                'verbose_name': 'ბროკერი',
                'verbose_name_plural': 'ბროკერები',
                'db_table': 'brokers',
            },
        ),
        migrations.CreateModel(
            name='BrokerAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_hash', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='API გასაღების ჰეში')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ბოლო გამოყენების თარიღი')),
            ],
            options={
                'verbose_name': 'API გასაღები',
                'verbose_name_plural': 'API გასაღებები',
                'db_table': 'broker_api_keys',
            },
        ),
        migrations.CreateModel(
            name='RejectedBidCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('estimated_delivery_time', models.IntegerField(verbose_name='მიწოდების დრო (საათებში)')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='უარყოფის თარიღი')),
            ],
            options={
                'verbose_name': 'უარყოფილი ბიდის კეში',
                'verbose_name_plural': 'უარყოფილი ბიდების კეში',
                'db_table': 'rejected_bids_cache',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='ბროკერის მიერ წარმოდგენილი კომპანია', max_length=200, verbose_name='კომპანიის დასახელება')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='ფასი')),
                ('estimated_delivery_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='მიწოდების დრო (საათებში)')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='კომენტარი')),
                ('contact_person', models.CharField(max_length=100, verbose_name='საკონტაქტო პირი')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='საკონტაქტო ტელეფონი')),
                ('status', models.CharField(choices=[('pending', 'მოლოდინში'), ('accepted', 'მიღებული'), ('rejected', 'უარყოფილი')], default='pending', max_length=20, verbose_name='სტატუსი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='metadata.currency', verbose_name='ვალუტა')),
            ],
            options={
                'verbose_name': 'ბიდი',
                'verbose_name_plural': 'ბიდები',
                'db_table': 'bids',
                'ordering': ['-created_at'],
            },
        ),
    ]
