# Generated by Django 5.0.1 on 2026-01-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('metadata', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='shipments.shipment', verbose_name='განაცხადი'),
        ),
        migrations.AddField(
            model_name='bid',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bids.broker', verbose_name='ბროკერი'),
        ),
        migrations.AddField(
            model_name='brokerapikey',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='bids.broker', verbose_name='ბროკერი'),
        ),
        migrations.AddField(
            model_name='rejectedbidcache',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_bid_cache', to='bids.broker', verbose_name='ბროკერი'),
        ),
        migrations.AddField(
            model_name='rejectedbidcache',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejected_bid_cache', to='metadata.currency', verbose_name='ვალუტა'),
        ),
        migrations.AddField(
            model_name='rejectedbidcache',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_bid_cache', to='shipments.shipment', verbose_name='განაცხადი'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['shipment', 'broker', 'status'], name='bids_shipmen_e81d2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='rejectedbidcache',
            constraint=models.UniqueConstraint(fields=('shipment', 'broker', 'price', 'estimated_delivery_time', 'currency'), name='unique_rejected_bid'),
        ),
    ]
