# Generated by Django 5.0.1 on 2026-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL for receiving bid status notifications', null=True, verbose_name='Webhook URL'),
        ),
    ]
