# Generated by Django 5.0.1 on 2026-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_add_broker_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerapikey',
            name='key',
            field=models.CharField(blank=True, help_text='ნამდვილი API გასაღები', max_length=100, null=True, verbose_name='API გასაღები'),
        ),
    ]
