# Generated by Django 5.0.1 on 2026-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_brokerapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerapikey',
            name='key',
            field=models.CharField(blank=True, help_text='შენახულია ღია ტექსტად ადმინ პანელში ჩვენებისთვის', max_length=128, null=True, verbose_name='API გასაღები'),
        ),
    ]
