# Generated by Django 5.0.1 on 2026-02-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_alter_brokerapikey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='webhook_url',
        ),
    ]
