# Generated by Django 5.0.1 on 2026-02-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_remove_broker_webhook_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'პლათფორმა', 'verbose_name_plural': 'პლათფორმები'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bids.broker', verbose_name='პლათფორმა'),
        ),
        migrations.AlterField(
            model_name='brokerapikey',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='bids.broker', verbose_name='პლათფორმა'),
        ),
        migrations.AlterField(
            model_name='rejectedbidcache',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_bid_cache', to='bids.broker', verbose_name='პლათფორმა'),
        ),
    ]
