# Generated by Django 5.0.1 on 2026-02-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_alter_broker_options_alter_bid_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='company_name',
            field=models.CharField(help_text='პლათფორმის მიერ წარმოდგენილი კომპანია', max_length=200, verbose_name='კომპანიის დასახელება'),
        ),
    ]
