# Generated by Django 5.0.1 on 2026-02-04 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_alter_bid_company_name'),
        ('metadata', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broker',
            new_name='Platform',
        ),
        migrations.AlterModelTable(
            name='platform',
            table='platforms',
        ),
        migrations.RenameModel(
            old_name='BrokerAPIKey',
            new_name='PlatformAPIKey',
        ),
        migrations.AlterModelTable(
            name='platformapikey',
            table='platform_api_keys',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='broker',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='rejectedbidcache',
            old_name='broker',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='platformapikey',
            old_name='broker',
            new_name='platform',
        ),
        migrations.RemoveConstraint(
            model_name='rejectedbidcache',
            name='unique_rejected_bid',
        ),
        migrations.RemoveIndex(
            model_name='bid',
            name='bids_shipmen_e81d2c_idx',
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['shipment', 'platform', 'status'], name='bids_shipmen_1bf070_idx'),
        ),
        migrations.AddConstraint(
            model_name='rejectedbidcache',
            constraint=models.UniqueConstraint(fields=('shipment', 'platform', 'price', 'estimated_delivery_time', 'currency'), name='unique_rejected_bid'),
        ),
    ]
