# Generated by Django 5.0.1 on 2026-02-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_platformapikey_remove_brokerapikey_broker_and_more'),
        ('metadata', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rejectedbidcache',
            name='unique_rejected_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='ID from the external platform to identify the specific broker', max_length=100, null=True, verbose_name='გარე მომხმარებლის ID'),
        ),
        migrations.AddField(
            model_name='rejectedbidcache',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='ID from the external platform to identify the specific broker', max_length=100, null=True, verbose_name='გარე მომხმარებლის ID'),
        ),
        migrations.AddConstraint(
            model_name='rejectedbidcache',
            constraint=models.UniqueConstraint(fields=('shipment', 'platform', 'price', 'estimated_delivery_time', 'currency', 'external_user_id'), name='unique_rejected_bid'),
        ),
    ]
