# Generated by Django 4.2.28 on 2026-02-05 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0011_add_platform_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='წაშლის თარიღი'),
        ),
        migrations.AddField(
            model_name='bid',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_bids', to=settings.AUTH_USER_MODEL, verbose_name='წაშალა'),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='წაშლილია'),
        ),
    ]
