# Generated by Django 4.2.28 on 2026-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0012_add_bid_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='display_id',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='ID'),
        ),
    ]
