# Generated by Django 4.2.28 on 2026-02-06 13:33

from django.db import migrations, models

def backfill_display_id(apps, schema_editor):
    Bid = apps.get_model('bids', 'Bid')
    
    # Check max existing ID
    max_id = Bid.objects.aggregate(models.Max('display_id'))['display_id__max'] or 0
    
    bids = Bid.objects.filter(display_id__isnull=True).order_by('created_at')
    for index, bid in enumerate(bids, start=max_id + 1):
        bid.display_id = index
        bid.save(update_fields=['display_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0013_bid_display_id'),
    ]

    operations = [
        migrations.RunPython(backfill_display_id),
    ]
