# Generated by Django 4.2.28 on 2026-02-16 12:28
from django.db import migrations


def convert_hours_to_minutes(apps, schema_editor):
    Bid = apps.get_model('bids', 'Bid')
    for bid in Bid.objects.all():
        if bid.estimated_delivery_minutes:
            bid.estimated_delivery_minutes = bid.estimated_delivery_minutes * 60
            bid.save(update_fields=['estimated_delivery_minutes'])

    RejectedBidCache = apps.get_model('bids', 'RejectedBidCache')
    for cache in RejectedBidCache.objects.all():
        if cache.estimated_delivery_minutes:
            cache.estimated_delivery_minutes = cache.estimated_delivery_minutes * 60
            cache.save(update_fields=['estimated_delivery_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0015_alter_bid_display_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='estimated_delivery_time',
            new_name='estimated_delivery_minutes',
        ),
        migrations.RenameField(
            model_name='rejectedbidcache',
            old_name='estimated_delivery_time',
            new_name='estimated_delivery_minutes',
        ),
        migrations.RunPython(convert_hours_to_minutes),
    ]