# Generated by Django 5.0.1 on 2026-01-30 23:58

import apps.shipments.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bids', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_location', models.TextField(help_text='ქალაქი, მისამართი', verbose_name='ტვირთის აღების ადგილი')),
                ('pickup_date', models.DateTimeField(validators=[apps.shipments.validators.validate_future_date], verbose_name='ტვირთის აღების თარიღი და დრო')),
                ('delivery_location', models.TextField(help_text='ქალაქი, მისამართი', verbose_name='ტვირთის ჩაბარების ადგილი')),
                ('cargo_volume', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='ტვირთის მოცულობა')),
                ('additional_conditions', models.TextField(blank=True, help_text='დამატებითი მოთხოვნები ან შენიშვნები', max_length=500, null=True, verbose_name='დამატებითი პირობები')),
                ('status', models.CharField(choices=[('active', 'აქტიური'), ('completed', 'დასრულებული'), ('cancelled', 'გაუქმებული')], default='active', max_length=20, verbose_name='სტატუსი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='დასრულების თარიღი')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='გაუქმების თარიღი')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_cargo', to='metadata.cargotype', verbose_name='ტვირთის ტიპი')),
                ('preferred_currency', models.ForeignKey(help_text='რომელ ვალუტაში მიიღებთ შეთავაზებებს', on_delete=django.db.models.deletion.PROTECT, related_name='shipments_currency', to='metadata.currency', verbose_name='სასურველი ვალუტა')),
                ('selected_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_shipment', to='bids.bid', verbose_name='არჩეული ბიდი')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_transport', to='metadata.transporttype', verbose_name='ტრანსპორტის ტიპი')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.user', verbose_name='განმცხადებელი')),
                ('volume_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_volume', to='metadata.volumeunit', verbose_name='მოცულობის ერთეული')),
            ],
            options={
                'verbose_name': 'განაცხადი',
                'verbose_name_plural': 'განაცხადები',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
