# Generated by Django 4.2.28 on 2026-02-06 13:33

from django.db import migrations, models

def backfill_display_id(apps, schema_editor):
    Shipment = apps.get_model('shipments', 'Shipment')
    
    # Check max existing ID
    max_id = Shipment.objects.aggregate(models.Max('display_id'))['display_id__max'] or 0
    
    shipments = Shipment.objects.filter(display_id__isnull=True).order_by('created_at')
    for index, shipment in enumerate(shipments, start=max_id + 1):
        shipment.display_id = index
        shipment.save(update_fields=['display_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_display_id'),
    ]

    operations = [
        migrations.RunPython(backfill_display_id),
    ]
