# Generated by Django 4.2.28 on 2026-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_backfill_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='display_id',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Display ID'),
        ),
    ]
